### ISSUE TITLE
random_line is effected by the length of lines

### ISSUE THREAD

**Issue by ChrisJefferson** [ps1dr3x/easy_reader#1]
In a file with lines of differing length, lines which are twice as long are twice as likely to be choosen.

I don't think there is any way to fix this with reasonable efficiency (I sometimes have to pick a random line, to do that I make a massive array with the position of the start of every line), but I think it should be mentioned in the docs fairly clearly, as I imagine most people would expect random_line to pick every line with equal chance?

**Comment by ps1dr3x** [comment]
Yeah you're right, I should mention it.

I believe that there is no effective solution to this problem, too. Enumerating the lines of a ~140GB file I'm working on takes like 30 minutes lol

Maybe i can add a new function (like... build_lines_index or build_index?) that builds the index of lines, making the following random_line calls perfectly distributed? I created this little library with the intent to mainly targeting large files and read them fast, so maybe this can be an optional step, but advices are welcome :smile: 

I'll surely think more about it!

**Comment by ps1dr3x** [comment]
Resolved in v0.3.0
